# Generated by Django 4.0.4 on 2022-05-20 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institute_infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_schedules', to='institute_infrastructure.group', verbose_name='Группа')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Нименование')),
                ('number', models.IntegerField(choices=[(1, '1. 8:00 - 9:30'), (2, '2. 9:50 - 11:20'), (3, '3. 11:40 - 13:10'), (4, '4. 13:20 - 14:50'), (5, '5. 15:10 - 16:40'), (6, '6. 16:50 - 18:20'), (7, '7. 16:50 - 18:20')], verbose_name='Номер пары')),
                ('lesson_type', models.IntegerField(choices=[(1, 'Лабораторная работа'), (2, 'Практика'), (3, 'Лекция')], verbose_name='Тип пары')),
                ('week_type', models.IntegerField(choices=[(1, 'Верхняя неделя'), (2, 'Нижняя неделя')], verbose_name='Тип недели')),
                ('week_day', models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота')], verbose_name='День недели')),
                ('begin', models.DateField(verbose_name='C')),
                ('end', models.DateField(verbose_name='По')),
                ('subgroup_number', models.IntegerField(default=0, verbose_name='Номер подгруппы (0 - для всех)')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='institute_infrastructure.building', verbose_name='Корпус')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='institute_infrastructure.classroom', verbose_name='Аудитория')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institute_infrastructure.discipline', verbose_name='Десциплина')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='institute_infrastructure.group', verbose_name='Группа')),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lesson_schedule.lessonschedule', verbose_name='Рапсиание')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institute_infrastructure.teacher', verbose_name='Преподаватель')),
            ],
        ),
    ]
