# Generated by Django 4.0.4 on 2022-05-22 05:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute_infrastructure', '0002_alter_classroom_building'),
        ('lesson_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institute_infrastructure.discipline', verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subgroup_number',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть меньше 0')], verbose_name='Номер подгруппы (0 - для всех)'),
        ),
    ]
